# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_P <- function(X, lambda) {
    .Call('MatrixFactorizationR_compute_P', PACKAGE = 'MatrixFactorizationR', X, lambda)
}

impute_lfmm_cpp <- function(Y, X, U, V, B, missingId) {
    invisible(.Call('MatrixFactorizationR_impute_lfmm_cpp', PACKAGE = 'MatrixFactorizationR', Y, X, U, V, B, missingId))
}

err2_lfmm_cpp <- function(Y, X, U, V, B) {
    .Call('MatrixFactorizationR_err2_lfmm_cpp', PACKAGE = 'MatrixFactorizationR', Y, X, U, V, B)
}

