# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_P <- function(X, lambda) {
    .Call('MatrixFactorizationR_compute_P', PACKAGE = 'MatrixFactorizationR', X, lambda)
}

